# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#
# Create list of countries along their ISO codes as reference, based on
# https://www.iban.com/country-codes
countries = {
  AF: %q{Afghanistan},
  AL: %q{Albania},
  DZ: %q{Algeria},
  AS: %q{American Samoa},
  AD: %q{Andorra},
  AO: %q{Angola},
  AI: %q{Anguilla},
  AQ: %q{Antarctica},
  AG: %q{Antigua and Barbuda},
  AR: %q{Argentina},
  AM: %q{Armenia},
  AW: %q{Aruba},
  AU: %q{Australia},
  AT: %q{Austria},
  AZ: %q{Azerbaijan},
  BS: %q{Bahamas (the)},
  BH: %q{Bahrain},
  BD: %q{Bangladesh},
  BB: %q{Barbados},
  BY: %q{Belarus},
  BE: %q{Belgium},
  BZ: %q{Belize},
  BJ: %q{Benin},
  BM: %q{Bermuda},
  BT: %q{Bhutan},
  BO: %q{Bolivia (Plurinational State of)},
  BQ: %q{Bonaire, Sint Eustatius and Saba},
  BA: %q{Bosnia and Herzegovina},
  BW: %q{Botswana},
  BV: %q{Bouvet Island},
  BR: %q{Brazil},
  IO: %q{British Indian Ocean Territory (the)},
  BN: %q{Brunei Darussalam},
  BG: %q{Bulgaria},
  BF: %q{Burkina Faso},
  BI: %q{Burundi},
  CV: %q{Cabo Verde},
  KH: %q{Cambodia},
  CM: %q{Cameroon},
  CA: %q{Canada},
  KY: %q{Cayman Islands (the)},
  CF: %q{Central African Republic (the)},
  TD: %q{Chad},
  CL: %q{Chile},
  CN: %q{China},
  CX: %q{Christmas Island},
  CC: %q{Cocos (Keeling) Islands (the)},
  CO: %q{Colombia},
  KM: %q{Comoros (the)},
  CD: %q{Congo (the Democratic Republic of the)},
  CG: %q{Congo (the)},
  CK: %q{Cook Islands (the)},
  CR: %q{Costa Rica},
  HR: %q{Croatia},
  CU: %q{Cuba},
  CW: %q{Curaçao},
  CY: %q{Cyprus},
  CZ: %q{Czechia},
  CI: %q{Côte d'Ivoire},
  DK: %q{Denmark},
  DJ: %q{Djibouti},
  DM: %q{Dominica},
  DO: %q{Dominican Republic (the)},
  EC: %q{Ecuador},
  EG: %q{Egypt},
  SV: %q{El Salvador},
  GQ: %q{Equatorial Guinea},
  ER: %q{Eritrea},
  EE: %q{Estonia},
  SZ: %q{Eswatini},
  ET: %q{Ethiopia},
  FK: %q{Falkland Islands (the) [Malvinas]},
  FO: %q{Faroe Islands (the)},
  FJ: %q{Fiji},
  FI: %q{Finland},
  FR: %q{France},
  GF: %q{French Guiana},
  PF: %q{French Polynesia},
  TF: %q{French Southern Territories (the)},
  GA: %q{Gabon},
  GM: %q{Gambia (the)},
  GE: %q{Georgia},
  DE: %q{Germany},
  GH: %q{Ghana},
  GI: %q{Gibraltar},
  GR: %q{Greece},
  GL: %q{Greenland},
  GD: %q{Grenada},
  GP: %q{Guadeloupe},
  GU: %q{Guam},
  GT: %q{Guatemala},
  GG: %q{Guernsey},
  GN: %q{Guinea},
  GW: %q{Guinea-Bissau},
  GY: %q{Guyana},
  HT: %q{Haiti},
  HM: %q{Heard Island and McDonald Islands},
  VA: %q{Holy See (the)},
  HN: %q{Honduras},
  HK: %q{Hong Kong},
  HU: %q{Hungary},
  IS: %q{Iceland},
  IN: %q{India},
  ID: %q{Indonesia},
  IR: %q{Iran (Islamic Republic of)},
  IQ: %q{Iraq},
  IE: %q{Ireland},
  IM: %q{Isle of Man},
  IL: %q{Israel},
  IT: %q{Italy},
  JM: %q{Jamaica},
  JP: %q{Japan},
  JE: %q{Jersey},
  JO: %q{Jordan},
  KZ: %q{Kazakhstan},
  KE: %q{Kenya},
  KI: %q{Kiribati},
  KP: %q{Korea (the Democratic People's Republic of)},
  KR: %q{Korea (the Republic of)},
  KW: %q{Kuwait},
  KG: %q{Kyrgyzstan},
  LA: %q{Lao People's Democratic Republic (the)},
  LV: %q{Latvia},
  LB: %q{Lebanon},
  LS: %q{Lesotho},
  LR: %q{Liberia},
  LY: %q{Libya},
  LI: %q{Liechtenstein},
  LT: %q{Lithuania},
  LU: %q{Luxembourg},
  MO: %q{Macao},
  MG: %q{Madagascar},
  MW: %q{Malawi},
  MY: %q{Malaysia},
  MV: %q{Maldives},
  ML: %q{Mali},
  MT: %q{Malta},
  MH: %q{Marshall Islands (the)},
  MQ: %q{Martinique},
  MR: %q{Mauritania},
  MU: %q{Mauritius},
  YT: %q{Mayotte},
  MX: %q{Mexico},
  FM: %q{Micronesia (Federated States of)},
  MD: %q{Moldova (the Republic of)},
  MC: %q{Monaco},
  MN: %q{Mongolia},
  ME: %q{Montenegro},
  MS: %q{Montserrat},
  MA: %q{Morocco},
  MZ: %q{Mozambique},
  MM: %q{Myanmar},
  NA: %q{Namibia},
  NR: %q{Nauru},
  NP: %q{Nepal},
  NL: %q{Netherlands (the)},
  NC: %q{New Caledonia},
  NZ: %q{New Zealand},
  NI: %q{Nicaragua},
  NE: %q{Niger (the)},
  NG: %q{Nigeria},
  NU: %q{Niue},
  NF: %q{Norfolk Island},
  MP: %q{Northern Mariana Islands (the)},
  NO: %q{Norway},
  OM: %q{Oman},
  PK: %q{Pakistan},
  PW: %q{Palau},
  PS: %q{Palestine, State of},
  PA: %q{Panama},
  PG: %q{Papua New Guinea},
  PY: %q{Paraguay},
  PE: %q{Peru},
  PH: %q{Philippines (the)},
  PN: %q{Pitcairn},
  PL: %q{Poland},
  PT: %q{Portugal},
  PR: %q{Puerto Rico},
  QA: %q{Qatar},
  MK: %q{Republic of North Macedonia},
  RO: %q{Romania},
  RU: %q{Russian Federation (the)},
  RW: %q{Rwanda},
  RE: %q{Réunion},
  BL: %q{Saint Barthélemy},
  SH: %q{Saint Helena, Ascension and Tristan da Cunha},
  KN: %q{Saint Kitts and Nevis},
  LC: %q{Saint Lucia},
  MF: %q{Saint Martin (French part)},
  PM: %q{Saint Pierre and Miquelon},
  VC: %q{Saint Vincent and the Grenadines},
  WS: %q{Samoa},
  SM: %q{San Marino},
  ST: %q{Sao Tome and Principe},
  SA: %q{Saudi Arabia},
  SN: %q{Senegal},
  RS: %q{Serbia},
  SC: %q{Seychelles},
  SL: %q{Sierra Leone},
  SG: %q{Singapore},
  SX: %q{Sint Maarten (Dutch part)},
  SK: %q{Slovakia},
  SI: %q{Slovenia},
  SB: %q{Solomon Islands},
  SO: %q{Somalia},
  ZA: %q{South Africa},
  GS: %q{South Georgia and the South Sandwich Islands},
  SS: %q{South Sudan},
  ES: %q{Spain},
  LK: %q{Sri Lanka},
  SD: %q{Sudan (the)},
  SR: %q{Suriname},
  SJ: %q{Svalbard and Jan Mayen},
  SE: %q{Sweden},
  CH: %q{Switzerland},
  SY: %q{Syrian Arab Republic},
  TW: %q{Taiwan (Province of China)},
  TJ: %q{Tajikistan},
  TZ: %q{Tanzania, United Republic of},
  TH: %q{Thailand},
  TL: %q{Timor-Leste},
  TG: %q{Togo},
  TK: %q{Tokelau},
  TO: %q{Tonga},
  TT: %q{Trinidad and Tobago},
  TN: %q{Tunisia},
  TR: %q{Turkey},
  TM: %q{Turkmenistan},
  TC: %q{Turks and Caicos Islands (the)},
  TV: %q{Tuvalu},
  UG: %q{Uganda},
  UA: %q{Ukraine},
  AE: %q{United Arab Emirates (the)},
  GB: %q{United Kingdom of Great Britain and Northern Ireland (the)},
  UM: %q{United States Minor Outlying Islands (the)},
  US: %q{United States of America (the)},
  UY: %q{Uruguay},
  UZ: %q{Uzbekistan},
  VU: %q{Vanuatu},
  VE: %q{Venezuela (Bolivarian Republic of)},
  VN: %q{Viet Nam},
  VG: %q{Virgin Islands (British)},
  VI: %q{Virgin Islands (U.S.)},
  WF: %q{Wallis and Futuna},
  EH: %q{Western Sahara},
  YE: %q{Yemen},
  ZM: %q{Zambia},
  ZW: %q{Zimbabwe},
  AX: %q{Åland Islands},
}
